# global settings
title: "Links"
description: "Links to pages"
permalink: "/:title"
url: https://chrisjacob.github.com/link
analytics_account: "UA-XXXXXXXXX"

# build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
